<a href="https://colab.research.google.com/github/ashajyothi-2005/Python-/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
arr

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr)
print(arr.ndim)
print(arr.shape)

[1 2 3 4 5 6 7]
1
(7,)


In [ ]:
import numpy as np
print(np.random. rand(3))
print(np.random.randn(3,3))

[0.53327936 0.47074122 0.66045014]
[[-0.18817625  0.02361104 -0.29919766]
 [-0.26493866 -0.80296056  0.12583268]
 [-0.31563196 -0.55000451 -0.28824615]]


In [ ]:
np.random.randint(10,20,4)

array([13, 18, 15, 15])

In [ ]:
import numpy as np
mat=np.array([[1,2,3,45,56],[9,4,5,6,7]])
print(mat)
print(mat.ndim)
print(mat.T)

[[ 1  2  3 45 56]
 [ 9  4  5  6  7]]
2
[[ 1  9]
 [ 2  4]
 [ 3  5]
 [45  6]
 [56  7]]


In [ ]:
print(np.zeros((4,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
print(np.ones((4,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
print(np.eye((4)))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
print(np.arange(0,10,3))

[0 3 6 9]


In [ ]:
print(np.linspace(0,1,3))

[0.  0.5 1. ]


In [ ]:
print(np.linspace(0,1,3).astype(int))

[0 0 1]


In [8]:
arr1= np. array([1, 2, 3])
arr2= np. array([4, 5, 6])
print(arr1+arr2)

[5 7 9]
